### ISSUE TITLE
[Feature Request] UserConfig.MAX_ACCOUNT_COUNT from 32 to infinity.

### ISSUE THREAD

**Issue by ArmeF97** [Nekogram/Nekogram#23]
I don't think it's too difficult to implement. Why having a client-side limit?

**Comment by rikakomoe** [comment]
Hi everyone!

I'm going to close this thread now because of inactivity of #24. Personally I feel this feature could be costly, in terms of potential conflicts, reduction of performance and more storage space required according to implementation introduced by #24. If any of you have any updates here, feel free to comment or open a new issue/pr.

Anyway, although we're not able to satisfy every feature request or accept all kinds of pull request, I have to thank @ArmeF97 's work. Nekogram is always open and community driven, we value every feedback, suggestion and contribution.

**Comment by ArmeF97** [comment]
You are right, as my first PR, it was a disaster. Nekogram is the first client that I successfully build with android studio (official telegram always crashed). I hope I'll be more of use in the future, with pr and issues. 

As of this particular feature request, I think that yes, it seemed a simple thing but it's not. 32, for now, it's ok.

Thanks everyone
