### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by airon90** [Nekogram/Nekogram#25]
As Nekogram is a GPL2 Android app, it may be added in [F-Droid](https://f-droid.org). Please follow the RfP [here](https://gitlab.com/fdroid/rfp/issues/1205)

**Comment by licaon-kter** [comment]
This fork needs to do the changes the FOSS project does: https://github.com/Telegram-FOSS-Team/Telegram-FOSS/ before thinking about being hosted on F-Droid.

**Comment by rikakomoe** [comment]
I understand there are people who consider Google services untrustworthy. However, the main concern here is that these changes,
- Do location sharing with OpenStreetMap(osmdroid) instead of Google Maps
- Use Twemoji emoji set instead of Apple's emoji
- Google Play Services GCM replaced with Telegram's push service

will bring down user experience so we don't officially make Nekogram FOSS.

I'm going to close this issue now. Maintaining a FOSS version is a long-term, frequent and heavy job: each time Telegram or Nekogram updates you'll have to resolve conflicts and merge them. If anyone would like to take charge of **maintaining** the FOSS version of Nekogram please feel free to tell me. If you do, I'll be happy to welcome you to the Nekogram dev team.

**Comment by licaon-kter** [comment]
@rikakomoe I agree with the last part, but

```
that these changes,
• Do location sharing with OpenStreetMap(osmdroid) instead of Google Maps
• Use Twemoji emoji set instead of Apple's emoji
• Google Play Services GCM replaced with Telegram's push service

will bring down user experience
```
...this is FUD! :-|
